#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop neosnatch-snapshot.timer >/dev/null || true
            deb-systemd-invoke stop neosnatch-snapshot.service >/dev/null || true
        fi
        ;;
    upgrade|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
